### ISSUE TITLE
Exception is thrown when a softbreak token is not surrounded by text-tokens

### ISSUE THREAD

**Issue by yamavol** [markdown-it/markdown-it-cjk-breaks#2]
This script 
```javascript
var md = require('markdown-it')();
var cjk = require('markdown-it-cjk-breaks')
var text = '![img](image.png)\ntext';
var conv = md.use(cjk).render(text)
console.log(conv);
```

throws an exception

```
TypeError: character.charCodeAt is not a function
```

This is because the plugin tries to run`eastAsianWidth(last)` in line55 even if `last` is not modified from 0x20. Here it the token-array when the exception was thrown.

![image](https://user-images.githubusercontent.com/38881625/49080063-c2593b00-f285-11e8-9f2c-e71a5ee3833e.png)

**Comment by rlidwka** [comment]
Yeah `last` should always be a character, not a charcode.

Fixed, thanks for reporting.
